name: Learn 365 Cloud Security

on:
  workflow_dispatch:
    
jobs:
  process_queue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Sed Test
        run: |
          sed -i "s|VPS|VPSTS|" README.md
          echo "$(cat README.md)"
